# Generated by Django 4.2.2 on 2024-12-24 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_country"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("can_block_user", "Возможность блокировки пользователя")],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
