# Generated by Django 5.1.2 on 2024-12-24 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_attempt",
                    models.DateTimeField(verbose_name="Дата и время попытки"),
                ),
                (
                    "status",
                    models.CharField(max_length=15, verbose_name="Статус попытки"),
                ),
                (
                    "server_response",
                    models.TextField(verbose_name="Ответ почтового сервера"),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailing",
                        to="mailing.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка",
                "verbose_name_plural": "Попытки",
                "ordering": ["date_attempt", "status"],
            },
        ),
    ]
