# Generated by Django 4.2.2 on 2024-12-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_alter_mailing_recipients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(
                help_text="Укажите получателей рассылки (используйте CTRL или COMMAND)",
                related_name="recipients",
                to="mailing.recipientmailing",
                verbose_name="Получатели",
            ),
        ),
    ]
