# Generated by Django 4.2.2 on 2024-12-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0007_alter_mailing_first_sending_alter_mailing_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipientmailing",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="mailing/avatars",
                verbose_name="Аватар",
            ),
        ),
    ]
