# Generated by Django 4.2.2 on 2024-12-24 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0010_mailing_is_active_mailing_owner_message_owner_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["first_sending"],
                "permissions": [("can_disable_mailing", "Возможность отключения рассылки")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
