# Generated by Django 5.1.3 on 2025-01-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="successful_attempt",
            field=models.IntegerField(default=0, verbose_name="Успешных попыток рассылки"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="total_attempt",
            field=models.IntegerField(default=0, verbose_name="Всего попыток рассылки"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="unsuccessful_attempt",
            field=models.IntegerField(default=0, verbose_name="Неуспешных попыток рассылки"),
        ),
    ]
