# Generated by Django 5.1.3 on 2025-01-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_users", "0002_customuser_successful_attempt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
