# Generated by Django 5.1.3 on 2025-01-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_users", "0007_alter_resetpassword_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewPassword",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "verbose_name": "новый пароль",
                "verbose_name_plural": "новый пароль",
                "db_table": "new_password",
            },
        ),
    ]
