# Generated by Django 5.1.3 on 2025-01-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_users", "0011_customuser_avatar_customuser_country_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [("can_view_all_custom_user_lists", "can view all custom_user lists")],
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
    ]
