# Generated by Django 5.1.2 on 2024-12-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=50, unique=True, verbose_name="Имя пользователя"),
        ),
    ]
