# Generated by Django 5.1.3 on 2025-01-13 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0003_mailing_created_by_message_created_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [("can_disable_mailing", "can disable mailing")],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
    ]
