# Generated by Django 5.1.3 on 2025-01-13 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0004_alter_mailing_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_disable_mailing", "can disable mailing"),
                    ("can_view_all_mailing_lists", "can view all mailing lists"),
                ],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [("can_view_all_message_lists", "can view all message lists")],
                "verbose_name": "письмо",
                "verbose_name_plural": "письма",
            },
        ),
        migrations.AlterModelOptions(
            name="recipientmailing",
            options={
                "permissions": [("can_view_all_recipient_lists", "can view all recipient lists")],
                "verbose_name": "получатель",
                "verbose_name_plural": "получатели",
            },
        ),
    ]
