# Generated by Django 5.1.3 on 2025-01-13 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0005_alter_mailing_options_alter_message_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="messages",
            field=models.ForeignKey(
                max_length=100,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="link_on_message",
                to="mailing_service.message",
                verbose_name="Письмо",
            ),
        ),
    ]
